[tool.ruff]
# Set the maximum line length
line-length = 100

# Enable Python 3.13 syntax
target-version = "py313"

[tool.ruff.lint]
# Enable these rule sets
select = [
    "E",   # pycodestyle errors
    "W",   # pycodestyle warnings
    "F",   # pyflakes (undefined names, unused imports, etc.)
    "I",   # isort (import sorting)
    "N",   # pep8-naming
    "UP",  # pyupgrade (use modern Python syntax)
    "B",   # flake8-bugbear (likely bugs)
    "A",   # flake8-builtins (shadowing built-ins)
    "C4",  # flake8-comprehensions
    "DTZ", # flake8-datetimez
    "T20", # flake8-print (no print statements in production)
    "RET", # flake8-return
    "SIM", # flake8-simplify
]

# Never enforce these rules
ignore = [
    "E501",  # Line too long (handled by formatter)
]

# Auto-fix when possible
fixable = ["ALL"]

[tool.ruff.lint.per-file-ignores]
# Allow print statements in test files
"**/test_*.py" = ["T20"]

[tool.mypy]
python_version = "3.13"
warn_return_any = true
warn_unused_configs = true
disallow_untyped_defs = true  # All functions must have type hints
