"""add metadata fields to statement

Revision ID: 79dc7c44b520
Revises: c01c1a7f3c07
Create Date: 2025-10-25 11:25:34.198944

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '79dc7c44b520'
down_revision: Union[str, None] = 'c01c1a7f3c07'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('statements', sa.Column('account_holder', sa.String(length=255), nullable=True))
    op.add_column('statements', sa.Column('account_number', sa.String(length=50), nullable=True))
    op.add_column('statements', sa.Column('balance', sa.String(length=50), nullable=True))
    op.add_column('statements', sa.Column('balance_date', sa.String(length=20), nullable=True))
    op.add_column('statements', sa.Column('period_start', sa.String(length=20), nullable=True))
    op.add_column('statements', sa.Column('period_end', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('statements', 'period_end')
    op.drop_column('statements', 'period_start')
    op.drop_column('statements', 'balance_date')
    op.drop_column('statements', 'balance')
    op.drop_column('statements', 'account_number')
    op.drop_column('statements', 'account_holder')
    # ### end Alembic commands ###
