"""migrate from pdf to csv support

Revision ID: c01c1a7f3c07
Revises: f886181bdeb0
Create Date: 2025-10-25 10:55:47.326435

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c01c1a7f3c07'
down_revision: Union[str, None] = 'f886181bdeb0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Add new columns as nullable first
    op.add_column('statements', sa.Column('file_type', sa.String(length=10), nullable=True))
    op.add_column('statements', sa.Column('raw_data', sa.Text(), nullable=True))
    op.add_column('statements', sa.Column('transactions', sa.JSON(), nullable=True))

    # Set default values for existing rows (if any)
    op.execute("UPDATE statements SET file_type = 'pdf' WHERE file_type IS NULL")
    op.execute("UPDATE statements SET raw_data = extracted_text WHERE raw_data IS NULL")
    op.execute("UPDATE statements SET transactions = '[]'::json WHERE transactions IS NULL")

    # Now make columns non-nullable
    op.alter_column('statements', 'file_type', nullable=False)
    op.alter_column('statements', 'raw_data', nullable=False)
    op.alter_column('statements', 'transactions', nullable=False)

    # Drop old column
    op.drop_column('statements', 'extracted_text')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('statements', sa.Column('extracted_text', sa.TEXT(), autoincrement=False, nullable=False))
    op.drop_column('statements', 'transactions')
    op.drop_column('statements', 'raw_data')
    op.drop_column('statements', 'file_type')
    # ### end Alembic commands ###
